### ISSUE TITLE
Linux uploads appear to be done by pelson?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/setuptools-feedstock#10]
This must simply be a matter of what token is used, but it appears all the Linux uploads for `setuptools` have been done by @pelson. Now I don't think this is actually the case as I have seen this right after the CI uploaded them. This doesn't appear to be the case with all feedstocks. `pip` for instance does not have this issue. Would be nice if we could correct this issue so as not to give the wrong impression about how these binaries were uploaded.

**Comment by pelson** [comment]
Thanks @jakirkham. This may have been one of the feedstocks I created by hand when we were having Travis issues. If that is the case, it could easily be that my BINSTAR_TOKEN bled into the feedstock creation phase (that is why we have automated this with CI, right 😉 ). Just so that I'm not the bottleneck and the BUS factor isn't 1, do you have access to https://anaconda.org/conda-forge/settings/access? In particular, there is a token which terminates with `86e1` which can be used.

**Comment by jakirkham** [comment]
Was wondering if that was the case. Appears I do and I can see the relevant token.

**Comment by jakirkham** [comment]
Though it does say something about AppVeyor. Guessing that is a red-herring 🐦.

**Comment by jakirkham** [comment]
So I think I need the tokens for the CIs too, right?

**Comment by pelson** [comment]
> So I think I need the tokens for the CIs too, right?

I suspect not. The "upload" information will come from the BINSTAR_TOKEN only.

**Comment by jakirkham** [comment]
Have added the new `BINSTAR_TOKEN`.

**Comment by jakirkham** [comment]
Just built the version `33.1.0` of `setuptools` on CircleCI and it uploaded correctly now showing `conda-forge` as the user instead of `pelson`. Looks like this is resolved.
